require('editor')
require('plugins')
require('lsp')
require('mapping')
require('fold')

require('plugin-config.treesitter')
require('plugin-config.autopairs')
require('plugin-config.neogit')
require('plugin-config.neorg')
require('plugin-config.toggleterm')
